from enum import StrEnum


class MediaStatus(StrEnum):
    PENDING = "PENDING"
    UPLOADING = "UPLOADING"
    UPLOADED_TEMP = "UPLOADED_TEMP"
    PROCESSING = "PROCESSING"
    UPLOADING_TELEGRAM = "UPLOADING_TELEGRAM"
    AVAILABLE = "AVAILABLE"
    FAILED = "FAILED"